### ISSUE TITLE
Webdriver helper

### ISSUE THREAD

**Issue by sagecelia** [cenfun/codeceptjs-monocart-coverage#1]
Hi, 

I used the codeceptjs-monocart-coverage plugin to perform a coverage test during my Codeceptjs tests. The Coverage plugin is only available with Playwright and Pupeteer, I wanted to use this plugin because I use the Webdriver helper.
Unfortunately I am no longer able to carry out my Codeceptjs test when I add the plugin to my codecept.conf.js. When I execute my npx codeceptjs run command I get this error which prevents the test from being executed:

**[MCR] Not found coverage data in dir(s):**

Here is the configuration of the plugin in codecept.conf.js : 
    **monocart: {
      require: 'codeceptjs-monocart-coverage',
      enabled: true,
      coverageOptions: {
        name: 'My CodeceptJS Coverage Report',
        outputDir: 'coverage-report',
      }
    }**

**Comment by cenfun** [comment]
CodeceptJS has integrated MCR, so this plugin is no longer maintained. but yes, it added support for Webdriver helper, can you provide more to reproduce this problem locally? seems the coverage data haven't been collected.

**Comment by cenfun** [comment]
It seems like I forgot to release the version, let me check

**Comment by sagecelia** [comment]
Thank you for your quick reply. But since coverage is not available for Webdriver, is there another way to perform coverage tests than this plugin if it is no longer maintained?

Here is my codecept.conf.js file:
```js
/** @type {CodeceptJS.MainConfig} */
exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    WebDriver: {
      url: '...',
      host: 'hub-selenium.***ch',
      path: '/',
      protocol: 'https',
      port: 443,
      browser: 'chrome',
      capabilities: {
        alwaysMatch: {
          browserName: 'chrome',
          acceptInsecureCerts: true
        }
      }
    }
  },
  include: {
    I: './steps_file.js'
  },
  name: 'codeceptjs-data-testid',
  plugins: {
    monocart: {
      require: 'codeceptjs-monocart-coverage',
      enabled: true,
      coverageOptions: {
        name: 'My CodeceptJS Coverage Report',
        outputDir: 'coverage-report',
      }
    },
    customLocator: {
      enabled: true,
      attribute: 'data-testid',
      startegy: 'css'
    },
    allure: {
      enabled: true,
      require: "allure-codeceptjs",
      outputDir: "output/allure-results",
      enableScreenshotDiffPlugin: true,
      addConsoleLogs: true,
      reportedEnvironmentVars: {
        browser: 'firefox'
      },
      addConsoleLogs: true
    }
  }
}
```

**Comment by cenfun** [comment]
did you got any errors when tesing?

**Comment by cenfun** [comment]
I'm sorry, I can't find the problem with just this configuration file.
I suggest submitting issues to [CodeceptJS](https://github.com/codeceptjs/CodeceptJS/issues)
and asked that CodeceptJS provide coverage support for WebDriver too.

**Comment by sagecelia** [comment]
Ok thank you, I open a new Topic on Codeceptjs Community. 
I don't really have any other specific configuration to share. Is there anything specific you're thinking of?

**Comment by cenfun** [comment]
In fact, I am not very familiar with WebDriver, so there might be some problems that I can't solve. Therefore, I still suggest that the Codeceptjs official provides coverage support for WebDriver.

**Comment by kobenguyent** [comment]
hey @sagecelia CodeceptJS would support the coverage WebDriver but only when you running with devtools protocol.

https://github.com/codeceptjs/CodeceptJS/pull/4349

@cenfun based on this wdio services, looks like we only support devtools protocol, right?
https://github.com/cenfun/wdio-monocart-service/blob/main/lib/index.js#L43

**Comment by cenfun** [comment]
@kobenguyent I think so.
For `wdio`, it actually collects the coverage data through the interface of `puppeteer`, and `puppeteer` should be using the `devtools` protocol.
